version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: wyd_arena_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: wyd
      POSTGRES_PASSWORD: wyd123
      POSTGRES_DB: wyd_arena
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
